# Generated by Django 4.2.7 on 2023-11-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-11-09'),
            preserve_default=False,
        ),
    ]
